version: '3.8'

services:
  mysql:
    image: mysql:8.0.40
    container_name: local-mysql

    # 컨테이너가 꺼졌을 때 재시작 여부 설정
    # - always: 무조건 항상 재시작
    # - unless-stopped: 사용자가 'docker stop' 명령으로 직접 멈춘 경우에는 재시작하지 않음
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root_password  # 루트 비밀번호
      MYSQL_DATABASE: messagesystem            # 생성할 데이터베이스
      MYSQL_USER: dev_user                # 사용자 계정
      MYSQL_PASSWORD: dev_password        # 사용자 비밀번호

    ports:
      - "13306:3306"
      # 호스트의 23306 → 컨테이너의 3306 (MySQL 기본 포트)

    volumes:
      - ./data/mysql:/var/lib/mysql
      # 컨테이너의 MySQL 데이터를 로컬 폴더와 연결하여 데이터 영속성 확보

  redis:
    image: redis:7.4.1
    restart: unless-stopped
    ports:
      - "16379:6379"
    volumes:
      - ./data/redis:/data

  redis-insight:
    image: redis/redisinsight:2.64.1
    restart: unless-stopped
    ports:
      - "15540:5540"
    volumes:
      - ./data/redis-insight:/data