spring:
  application:
    name: message-system-add-channel
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:13306/messagesystem
      username: dev_user
      password: dev_password
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: ConnectionPool
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 60000
      connection-timeout: 30000
      url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always # resource/schema.sql? ????. 	spring.sql.init.mode=always? ???? ??? ???? ???

  data:
    redis:
      host: localhost
      port: 16379 # redis? ?? ??? 6379??, db port? 10000??? ???? ?? ??? ??? ???? ??
      repositories:
        enabled: false # ? ??? ?? ??: ???? bean? ???? ?? ???

logging:
  level:
    com.zaxxer.hikari: debug